BUILD_GAME_QVM=0
BUILD_GAME_SO=1
BUILD_SERVER=0
BUILD_CLIENT=1
BUILD_CLIENT_SMP=0
BUILD_STANDALONE=1
BUILD_KAAS=0
USE_LOCAL_HEADERS=1
USE_CURL=1

USE_CODEC_VORBIS=1
USE_INTERNAL_VORBIS=0

# dont disable this for mingw build !
USE_INTERNAL_GLEW=1

USE_FREETYPE=1
USE_FREETYPE_BUILDIN=0
USE_MUMBLE=0
USE_SSE=1
USE_OPENMP=0
USE_CIN_THEORA=1
USE_CIN_THEORA_BUILDIN=0
# if 1 cgame, game and ui dll compiles c-language, otherwise c++
USE_C_DLL=1

USE_INTERNAL_PNG=0
USE_INTERNAL_JPG=1

# for kaas built deactivate this
USE_ASM_LIB=1
#libfreetype is linked with zlib so USE_INTERNAL_ZLIB only makes sense
#if USE_FREETYPE_BUILDIN is enabled as well
USE_INTERNAL_ZLIB=1

USE_UNSAFE_OPTIMIZATIONS=0

USE_VOIP=1
USE_INTERNAL_SPEEX=1

USE_CPLUS_0X = 0
# verursacht compilefehler in  /cl_cgame.c wenn 0

