#!/bin/sh
#
# @(#)postinstall	$Id: postinstall,v 1.3 2006/01/21 12:54:52 coyote Exp $
#
# postinstall script for kingpinq3

kingpinq3_dir=$BASEDIR/kingpinq3
dest_dir=${PKG_INSTALL_ROOT}/usr/local/bin

if [ -d ${dest_dir} ]; then
	for inst_script in kpq3ded.sh kingpinq3.sh
	do
		dest_script=${dest_dir}/${inst_script}
		if [ ! -h ${dest_script} ]; then
			ln -s ${kingpinq3_dir}/${inst_script} ${dest_script}
		fi
	done
fi

exit 0

